"""
CBM Anomaly Detection Dashboard - Configuration
"""

# MLflow Configuration
# Run ID is resolved automatically (latest IsolationForest run in the experiment).
# Set MLFLOW_RUN_ID to a specific run id string to pin a model version.
# sqlite is the MLflow 3.x default; the legacy ./mlruns file store is deprecated there.
MLFLOW_TRACKING_URI = "sqlite:///mlflow.db"
MLFLOW_EXPERIMENT_NAME = "CBM_Shaft_Anomaly_Detection"
MLFLOW_RUN_ID = None

# Data Configuration
# Real sensor data (proprietary) or synthetic benchmark data
# generated by evaluation/synthetic_data_generator.py
DATA_PATH = "preprocessed_shaft_data.parquet"

# Model Configuration
ANOMALY_THRESHOLD = -0.50  # Isolation Forest score threshold (lower = more anomalous)
CONTAMINATION_RATE = 0.05  # expected anomaly rate used at training time

# Alert Configuration
ALERT_ENABLED = True
ALERT_THRESHOLD_Z_SCORE = 3.0  # per-feature z-score that triggers an alert
ALERT_EMAIL = "maintenance@example.com"  # placeholder shown in Settings page

# Deployment placeholders (displayed in the Settings page; used only when deploying)
AWS_REGION = "ap-northeast-2"
AWS_S3_BUCKET = "cbm-anomaly-models"
AWS_ECR_REPOSITORY = "cbm-dashboard"
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "cbm_monitoring"
DB_USER = "cbm_user"

# Dashboard Configuration
PAGE_TITLE = "Ship Shaft CBM Monitoring"
PAGE_ICON = ":material/directions_boat:"
LAYOUT = "wide"
REFRESH_INTERVAL = 60  # seconds
MAX_HISTORY_DAYS = 30
BATCH_SIZE = 1000
